### ISSUE TITLE
Add code duplication pre-commit hook

### ISSUE THREAD

**Issue by cjgrady** [lifemapper/lm_test#31]
**Is your feature request related to a problem? Please describe.**
We don't have a way to prevent code duplication right now.

**Describe the solution you'd like**
I used the [Jscpd](https://github.com/kucherenko/jscpd) package via `super-linter` before but it doesn't look to be directly supported by pre-commit at the moment.  I do think that it is possible to do that though.  If not, we could include super-linter on a GitHub action on pull request maybe.

**Describe alternatives you've considered**
Super-linter did this by default.  That is the only thing I haven't been able to do (yet) with pre-commit.

**Comment by cjgrady** [comment]
Any experience with this @maxpatiiuk?  There may be another tool that we can use with pre-commit that does this as well.

**Comment by maxpatiiuk** [comment]
I created a mirror of jscpd for pre-commit using [pre-commit-mirror-maker](https://github.com/pre-commit/pre-commit-mirror-maker)
Here is the URL: https://github.com/maxpatiiuk/mirrors-jscpd

Basically, just add this to your `.pre-comit-config.yaml`:
```yaml
  - repo: https://github.com/maxpatiiuk/mirrors-jscpd
    rev: v3.3.25
    hooks:
      - id: jscpd
        types: [text]
```
